CUDA_LAUNCH_BLOCKING=1 CUDA_VISIBLE_DEVICES=0 python supernet_train.py \
--data-set CIFAR10 \
--data-path /home/hanjing/CHE/SpikeDHS_CLA/data \
--gp \
--change_qk \
--relative_position \
--mode super \
--dist-eval \
--cfg ./experiments/supernet/supernet-T.yaml \
--resume logs/pretrained_model/supernet-tiny.pth \
--epochs 1000 \
--warmup-epochs 10 \
--batch-size 64 \
--experiment_description 'train supernet: from imagenet checkpoint train' \
--opt sgd \
--weight-decay 1e-8 \
--lr 1e-2 \