CUDA_LAUNCH_BLOCKING=1 CUDA_VISIBLE_DEVICES=0 python supernet_train.py \
--data-set CIFAR10 \
--data-path /home/hanjing/CHE/SpikeDHS_CLA/data \
--gp \
--relative_position \
--mode super \
--dist-eval \
--cfg ./experiments/supernet/supernet-Spikformer.yaml \
--batch-size 64 \
--experiment_description 'train supernet: auto-spikformer structure=spikformer' \
--opt adamw \
--weight-decay 6e-2 \
--lr 5e-4 \
--min-lr 1e-5 \
--sched cosine \
--patch_size 4 \
--input-size 32 \
--batch-size 128 \
--warmup-epochs 20 \
--warmup-lr 1e-5 \
--epochs 1000 \
--mixup 0.5 \
--mixup-off-epoch 200 \
--cutmix 0 \
--remode const \
--color-jitter 0 \